version: '3.8'
services:
  web:
    image: my-vite-react-mpa:latest
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_CONTACT_EMAIL=contact@example.com
    volumes:
      - ./public/images:/app/dist/images
    restart: unless-stopped